CREATE DATABASE IF NOT EXISTS patro_db CHARACTER SET 'utf8';
USE patro_db;

CREATE TABLE IF NOT EXISTS inscris (
    id_inscris INT (11) AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(50) NOT NULL,
    prénom VARCHAR(255) NOT NULL,
    date_naissance DATE NOT NULL,
    adresse VARCHAR(255) NOT NULL,
    genre VARCHAR(10) NOT NULL,
    section VARCHAR(20) NOT NULL,
    tel INT(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS annee(
    idannee INT AUTO_INCREMENT PRIMARY KEY,
    annee INT NOT NULL
) ENGINE=InnoDB;

DROP TABLE IF EXISTS admin;
CREATE TABLE IF NOT EXISTS admin (
    id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL DEFAULT 'patro',
    pwd VARCHAR(255) NOT NULL DEFAULT '1234',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    etat INT NOT NULL DEFAULT 1,
    type VARCHAR(30) NOT NULL DEFAULT 'super_admin',
    last_login TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3;